import apiService from "./api/apiService";
import {getHeaders} from "./api/headers";

function getFeedbacks(idSources = undefined,
                      allFilters,
                      columns,
                      simplified,
                      code,
                      skip,
                      limit,
                      sort,
                      search,
                      download,
                      returnFormatted,
                      typeDownload,
                      antTable,
                      idMetadata,
                      words=null,
                      lemmas = null,
                      returnAnt = true,
                      wordFilter = undefined
) {
    const {startDate, endDate, selectedLocation, selectedChannel, selectedTopics, selectedProducts, selectedSource, customFilters} = allFilters;

    const body = {
        idSources: idSources ? idSources : selectedSource,
        columns,
        channels: selectedChannel,
        simplified,
        code,
        skip,
        limit,
        sort,
        search,
        customFilters: wordFilter ? wordFilter : customFilters,
        download,
        returnFormatted,
        typeDownload,
        startDate,
        endDate,
        idLocations: selectedLocation,
        idTopics: selectedTopics,
        antTable,
        idMetadata,
        idProducts: selectedProducts,
        words,
        lemmas,
        returnAnt
    }
    return apiService.apiFeedback.post('getFeedback', body, getHeaders(false, true))
}
function editFeedbackSentiment(idFeedback,
                               textRisposta,
                               sourceFrom,
                               urlToAnsw,
                               idSource,
                               idSmartResponse,
                               sentiment,
                               autoGeneratedGPT) {

    const body = {
        idFeedback,
        textRisposta,
        sourceFrom,
        urlToAnsw,
        idSource,
        idSmartResponse,
        sentiment,
        autoGeneratedGPT
    }
    return apiService.apiUrl.post('editFeedback/edit', body, getHeaders())
}

function getFeedbackFromGraph(allFilters,
                              words,
                              code) {
    const {startDate, endDate, selectedLocation, selectedChannel, selectedTopics, selectedSource} = allFilters;

    const body = {
        idSources: selectedSource,
        words,
        channels: selectedChannel,
        code,
        endDate,
        idLocations: selectedLocation,
        idTopics: selectedTopics,
        startDate
    }
    return apiService.apiFeedback.post('getFeedbackFromGraph', body, getHeaders())
}

function replyFeedbackFacebook(resp,
                               idFeedback,
                               urlPart,
                               idSource,
                               idSmartResponse) {

    const body = {
        resp,
        idFeedback,
        urlPart,
        idSource,
        idSmartResponse
    }
    return apiService.facebookApi.post('/replyReview', body, getHeaders())
}

function replyFeedbackGoogle(resp,
                             idFeedback,
                             urlPart,
                             idSource,
                             idSmartResponse) {
    const body = {
        resp,
        idFeedback,
        urlPart,
        idSource,
        idSmartResponse
    }
    return apiService.googleApi.post('/replyReview', body, getHeaders())
}

function getInfoFeedbacks(idSources = undefined,
                          allFilters,
                          columns,
                          simplified,
                          code,
                          skip,
                          limit,
                          sort,
                          search,
                          download,
                          returnFormatted,
                          typeDownload,
                          antTable,
                          idMetadata,
                          words,
                          lemmas,
                          returnAnt,
                          wordFilter = undefined
    ) {
    const {startDate, endDate, selectedLocation, selectedTopics, selectedSource, customFilters, selectedChannel, selectedProducts} = allFilters;

    const body = {
        idSources: idSources ? idSources : selectedSource,
        columns,
        channels: selectedChannel,
        simplified,
        code,
        skip,
        limit,
        sort,
        search,
        customFilters: wordFilter ? wordFilter : customFilters,
        download,
        returnFormatted,
        typeDownload,
        startDate,
        endDate,
        idLocations: selectedLocation,
        idTopics: selectedTopics,
        antTable,
        idMetadata,
        idProducts: selectedProducts,
        words,
        lemmas,
        returnAnt
    }
    return apiService.apiFeedback.post('getInfo', body, getHeaders())
}

const FeedbackService = {
    getFeedbacks,
    getInfoFeedbacks,
    editFeedbackSentiment,
    replyFeedbackFacebook,
    replyFeedbackGoogle,
    getFeedbackFromGraph
}

export default FeedbackService
