import React, { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import ServiceWrapper from '../../../helpers/ServiceWrapper'
import { selectAllFilters } from '../../../store/selectors/selectorsSlice'
import { useTranslation } from 'react-i18next'
import PageContainer from '../../../components/PageComponents/PageContainer/PageContainer'
import PageHeader from '../../../components/PageComponents/PageHeader/PageHeader'
import { RootState } from '../../../store/store'
import DonutCard from '../../../components/DonutCard/DonutCard'
import InfoCard from '../../../components/InfoCard/InfoCard'
import TierListCard from '../../../components/TierListCard/TierListCard'
import styles from './HomeSurveys.module.scss'
import ReviewCard from '../../../components/Cards/ReviewCard/ReviewCard'
import Button from '../../../components/Button/Button'
import PageNavigator from '../../../components/PageNavigator/PageNavigator'
import { getNoCodeFromPlatfrom } from '../../../helpers/helpers'
import FeedbackService from '../../../services/FeedbackService'
import { PaginationState } from '@tanstack/react-table'
import search from '../../../store/search/search'
import SmartResponseService from '../../../services/SmartResponseService'
import TopicService from '../../../services/TopicService'
import { showToast } from '../../../store/toast/errorToastSlice'
import ScraperService from '../../../services/ScraperService'
import _ from 'lodash'
import TrackerCard from '../../../components/TrackerCard/TrackerCard'
import CardSurvey from '../../../components/Cards/SurveyCard/SurveyCard'
import moment from 'moment'
import HomeService from '../../../services/HomeService'
function Reviews() {
    const allFilters = useSelector(selectAllFilters)

    const { t } = useTranslation()

    const tierList = [
        {
            label: 'The Fork',
            icon: 'TheFork.svg',
        },
        {
            label: 'Facebook',
            icon: 'Facebook.svg',
        },
        {
            label: 'Tripadvisor',
            icon: 'TripadvisorAPI.svg',
        },
    ]

    /*const surveys = [
        {
            _id: '649c0da161f64b7b8337055f',
            createdAt: '2023-06-28T10:38:25.236000+00:00',
            name: 'TETS - Corso Sardegna, 165, 16142 Genova GE, Italia',
            locationID: '6491ca7abd5a8c252d6186bc',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: 'Corso Sardegna, 165, 16142 Genova GE, Italia',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'go5dvQmR',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [],
            },
            children: null,
        },
        {
            _id: '64a285e3ed2f45786a63f2d5',
            createdAt: '2023-07-03T08:25:07.231000+00:00',
            name: 'test - Corso Sardegna, 165, 16142 Genova GE, Italia',
            locationID: '6491ca7abd5a8c252d6186bc',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: 'Corso Sardegna, 165, 16142 Genova GE, Italia',
            statusAnalisi: 1,
            timestampAnalisi: '2023-07-03T14:46:49.696000+00:00',
            from: 'giggi spa',
            code: 4,
            columns: [
                {
                    id: 'd4S4JeKhVi80',
                    name: 'allora? come???',
                    type: 'rating',
                    varsType: 'integer',
                    isRating: true,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 'iekGVVw9rFZ2',
                    name: 'analizziamo; tutto qua?',
                    type: 'short_text',
                    varsType: 'string',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: true,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 'mHa9lhU5Ocml',
                    name: 'Con quale probabilità ci consiglieresti a un amico o a un collega?',
                    type: 'nps',
                    varsType: 'integer',
                    isRating: false,
                    isNPS: true,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 1,
                    name: 'data_risposta',
                    type: 'mydatetime',
                    varsType: 'datetime',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: true,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 2,
                    name: 'data_inizio_risposta',
                    type: 'datetime',
                    varsType: 'datetime',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 3,
                    name: 'durata',
                    type: 'time',
                    varsType: 'timestamp',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 'fkkpbeorih',
                    name: 'Sent_;;;',
                    type: 'integer',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: true,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                },
                {
                    id: 'hjwhemgrqq',
                    name: 'topics_;;;',
                    type: 'list',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: true,
                },
                {
                    id: 'kgraeedwfy',
                    name: 'Sent_analizziamo; tutto qua?',
                    type: 'integer',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: true,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                },
                {
                    id: 'jnbrbbulgw',
                    name: 'topics_analizziamo; tutto qua?',
                    type: 'list',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: true,
                },
            ],
            typeformID: 'LsdjQXsW',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 11,
                    completion_rate: 100,
                    responses_count: 2,
                    total_visits: 3,
                    unique_visits: 1,
                },
                fields: [
                    {
                        id: 'd4S4JeKhVi80',
                        title: 'allora? come???',
                        label: '1',
                        ref: '9df5311b-3efc-412f-91ef-12534bfb9d10',
                        views: 5,
                        dropoffs: 2,
                        type: 'rating',
                    },
                    {
                        id: 'iekGVVw9rFZ2',
                        title: 'analizziamo. tutto qua?',
                        label: '2',
                        ref: 'e8cdcee4-8d58-4593-93c3-156773c0bf31',
                        views: 3,
                        dropoffs: 1,
                        type: 'short_text',
                    },
                    {
                        id: 'mHa9lhU5Ocml',
                        title: 'Con quale probabilità ci consiglieresti a un amico o a un collega?',
                        label: '3',
                        ref: '826809ac-d273-46c8-b625-38fb3eb7b64b',
                        views: 2,
                        dropoffs: 0,
                        type: 'nps',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '64b564925e9e5dc039686700',
            createdAt: '2023-07-17T15:56:02.737000+00:00',
            name: 'testste - Corso Sardegna, 165, 16142 Genova GE, Italia',
            locationID: '6491ca7abd5a8c252d6186bc',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: 'Corso Sardegna, 165, 16142 Genova GE, Italia',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'G2axlL6m',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [
                    {
                        id: 'AZoRcAfE48IZ',
                        title: 'ciao\n',
                        label: '1',
                        ref: '01H5J923HZ369K8S0QNV2F69NR',
                        views: 6,
                        dropoffs: 5,
                        type: 'short_text',
                    },
                    {
                        id: 'KKGxUh8vJjsl',
                        title: 'test',
                        label: '2',
                        ref: '01H5J92MBA2G2MDR2AF7A34874',
                        views: 4,
                        dropoffs: 4,
                        type: 'multiple_choice',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '64be9da995144cb88abc9b99',
            createdAt: '2023-07-24T15:50:01.942000+00:00',
            name: 'New survey Jim - Via Plinio, 153, 80045 Pompei (NA)',
            locationID: '64a53c6d04ffcb4c4db5c35d',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: 'Via Plinio, 153, 80045 Pompei (NA)',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'bRW5cO79',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 16,
                    completion_rate: 100,
                    responses_count: 1,
                    total_visits: 2,
                    unique_visits: 1,
                },
                fields: [
                    {
                        id: 'OCUiCzlrZiPp',
                        title: "What's your favorite food?",
                        label: '1',
                        ref: '01H649H55DEMDPK976A186V199',
                        views: 7,
                        dropoffs: 5,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'Wdh9A7kTOQKA',
                        title: 'How many users do you have ?',
                        label: '2',
                        ref: '01H649GF6HJRJWC40XP0AN9BMF',
                        views: 6,
                        dropoffs: 5,
                        type: 'short_text',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '64c1150b71e8b73ab04f548a',
            createdAt: '2023-07-26T12:43:55.307000+00:00',
            name: 'test - Via Roma, 69/73, 84121 Salerno SA, Italia',
            locationID: '6470bf528b738d53d0aaa4fb',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: 'Via Roma, 69/73, 84121 Salerno SA, Italia',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'wUuLmIxs',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [
                    {
                        id: '4JmZW3htzgov',
                        title: 'how is Jim?',
                        label: '1',
                        ref: '01H693NMADR2RS6CT0XC7HTHYP',
                        views: 10,
                        dropoffs: 9,
                        type: 'rating',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '64c23bee5b17e6021d83ad8e',
            createdAt: '2023-07-27T09:42:06.330000+00:00',
            name: "jim's new survey - Via Appia, 42, 83042 Atripalda AV, Italia",
            locationID: '64a540523b2a5e9f4432cb5f',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: 'Via Appia, 42, 83042 Atripalda AV, Italia',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'gTLcfCLz',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [
                    {
                        id: 'va3EddQOaSdB',
                        title: '',
                        label: '1',
                        ref: '01H6HNRA5EQXZS6K3TH58YP8D8',
                        views: 14,
                        dropoffs: 14,
                        type: 'short_text',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '64c585dc068408833c4f7f0f',
            createdAt: '2023-07-29T21:34:20.942000+00:00',
            name: 'new test  - Viale Col di Lana, 2, 20136 Milano (MI)',
            locationID: '64b79b997448d322a128858b',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: 'Viale Col di Lana, 2, 20136 Milano (MI)',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'MnbnKTfn',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [
                    {
                        id: 'S7rWwblD1nw1',
                        title: '',
                        label: '1',
                        ref: '01H6XP3HPNA0MC10YECXGW625T',
                        views: 19,
                        dropoffs: 18,
                        type: 'opinion_scale',
                    },
                    {
                        id: 'tlF40xbmbyZT',
                        title: '',
                        label: '2',
                        ref: '01H6XP71549GYP6CWJ7C73719F',
                        views: 17,
                        dropoffs: 16,
                        type: 'short_text',
                    },
                    {
                        id: 'grinAn3e04Bt',
                        title: '',
                        label: '3',
                        ref: '01H6XP3BBD9XPJKTJ4BNPAAPEV',
                        views: 37,
                        dropoffs: 35,
                        type: 'rating',
                    },
                    {
                        id: '0JzYWdj0UTJQ',
                        title: '',
                        label: '4',
                        ref: '01H6V2X9WTW4GQ3KPMBMXY5QQM',
                        views: 27,
                        dropoffs: 26,
                        type: 'short_text',
                    },
                    {
                        id: 'iQlnRGAAbLAn',
                        title: '',
                        label: '5',
                        ref: '01H6XPBRXBQ9RS70P8MZ9208EF',
                        views: 4,
                        dropoffs: 3,
                        type: 'opinion_scale',
                    },
                    {
                        id: 'cCrMz3J5xeO5',
                        title: '',
                        label: '6',
                        ref: '01H6XPBJHDDXJ6TM0AXQWAJ4WM',
                        views: 7,
                        dropoffs: 6,
                        type: 'rating',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '64ef05417cd2437a380ad08a',
            createdAt: '2023-08-30T09:00:49.952000+00:00',
            name: 'test - 86, 35126 Padova (PD)',
            locationID: '64b79b970a7793662b065ef9',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: '86, 35126 Padova (PD)',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'aTzdc9UM',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [],
            },
            children: null,
        },
        {
            _id: '64ef1cb71dc464a4afa362a2',
            createdAt: '2023-08-30T12:40:55.186000+00:00',
            name: 'Tutto giusto? - 86, 35126 Padova (PD)',
            locationID: '64b79b970a7793662b065ef9',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: '86, 35126 Padova (PD)',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'e0zvfu6R',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [
                    {
                        id: 'WxWnO42FJMu6',
                        title: '*È la tua prima volta da Panino Giusto?*',
                        label: '1',
                        ref: '01H7HZYADWA9J16BYBVMXB7R9Q',
                        views: 32,
                        dropoffs: 32,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'WDikME4SDT5f',
                        title: '*Con chi sei venuto a trovarci oggi?*',
                        label: '2',
                        ref: '01H7J05GZ41M1F06BBXNYE93DK',
                        views: 0,
                        dropoffs: 0,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'SO2gICETLuFW',
                        title: '*Quanti anni hai?*',
                        label: '3',
                        ref: '01H7HZX2WQ3Y1B83JP1ZBF96AC',
                        views: 0,
                        dropoffs: 0,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'XMlp7hjKGjdi',
                        title: '*Come valuti il servizio di oggi?*',
                        label: '4',
                        ref: '01H7J0EB1SJQW4ZY5ZCGCKN4GV',
                        views: 0,
                        dropoffs: 0,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'O3do9xinREHN',
                        title: '*La cosa più importante: hai mangiato bene?*',
                        label: '5',
                        ref: '01H7J1GCF0CS022ARBB8QRB7W1',
                        views: 0,
                        dropoffs: 0,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'H2cN67CSdhTq',
                        title: '*Siamo felici di averti soddisfatto*\n*Vuoi lasciarci una recensione su Google?*',
                        label: '6',
                        ref: '1119b544-99d2-4c79-b7a8-9e2803d0f657',
                        views: 0,
                        dropoffs: 0,
                        type: 'yes_no',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '64f0aa11ccbfd8d10bb30170',
            createdAt: '2023-08-31T16:56:17.648000+00:00',
            name: 'Tutto giusto? - Via Martiri della Loggia, 50, 84010 San Marzano Sul Sarno SA, Italia',
            locationID: '6475c5b4f80088e7c7400d16',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address:
                'Via Martiri della Loggia, 50, 84010 San Marzano Sul Sarno SA, Italia',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'survey',
            code: 4,
            columns: [
                {
                    id: '4H9xNPz57KMY',
                    name: '*È la tua prima volta da Panino Giusto?*',
                    type: 'multiple_choice',
                    varsType: 'list',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: true,
                },
                {
                    id: 'xRdPFN92JfDS',
                    name: '*Con chi sei venuto a trovarci oggi?*',
                    type: 'multiple_choice',
                    varsType: 'list',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: true,
                },
                {
                    id: 'aozNYor1i3ej',
                    name: '*Quanti anni hai?*',
                    type: 'multiple_choice',
                    varsType: 'list',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: true,
                },
                {
                    id: 'FVboXhGWPGkL',
                    name: '*Come valuti il servizio di oggi?*',
                    type: 'multiple_choice',
                    varsType: 'list',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: true,
                },
                {
                    id: 'QNXBgdC8uxvB',
                    name: '*La cosa più importante: hai mangiato bene?*',
                    type: 'multiple_choice',
                    varsType: 'list',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: true,
                },
                {
                    id: 'gnkBBXfvLHr8',
                    name: '*Siamo felici di averti soddisfatto* *Vuoi lasciarci una recensione su Google?*',
                    type: 'yes_no',
                    varsType: 'boolean',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 1,
                    name: 'data_risposta',
                    type: 'mydatetime',
                    varsType: 'datetime',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: true,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 2,
                    name: 'data_inizio_risposta',
                    type: 'datetime',
                    varsType: 'datetime',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 3,
                    name: 'durata',
                    type: 'time',
                    varsType: 'timestamp',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
            ],
            typeformID: 'F2o1TdAP',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 13,
                    completion_rate: 20,
                    responses_count: 1,
                    total_visits: 6,
                    unique_visits: 5,
                },
                fields: [
                    {
                        id: 'aozNYor1i3ej',
                        title: '*Quanti anni hai?*',
                        label: '1',
                        ref: '01H7HZX2WQ3Y1B83JP1ZBF96AC',
                        views: 50,
                        dropoffs: 44,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'xRdPFN92JfDS',
                        title: '*Con chi sei venuto a trovarci oggi?*',
                        label: '2',
                        ref: '01H7J05GZ41M1F06BBXNYE93DK',
                        views: 7,
                        dropoffs: 2,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'FVboXhGWPGkL',
                        title: '*Come valuti il servizio di oggi?*',
                        label: '3',
                        ref: '01H7J0EB1SJQW4ZY5ZCGCKN4GV',
                        views: 5,
                        dropoffs: 1,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'QNXBgdC8uxvB',
                        title: '*La cosa più importante: hai mangiato bene?*',
                        label: '4',
                        ref: '01H7J1GCF0CS022ARBB8QRB7W1',
                        views: 4,
                        dropoffs: 3,
                        type: 'multiple_choice',
                    },
                    {
                        id: '4H9xNPz57KMY',
                        title: '*È la tua prima volta da Panino Giusto?*',
                        label: '5',
                        ref: '01H7HZYADWA9J16BYBVMXB7R9Q',
                        views: 6,
                        dropoffs: 5,
                        type: 'multiple_choice',
                    },
                    {
                        id: 'gnkBBXfvLHr8',
                        title: '*Siamo felici di averti soddisfatto*\n*Vuoi lasciarci una recensione su Google?*',
                        label: '6',
                        ref: '1119b544-99d2-4c79-b7a8-9e2803d0f657',
                        views: 1,
                        dropoffs: 0,
                        type: 'yes_no',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '651559e704fc8e45e6387e1b',
            createdAt: '2023-09-28T10:48:07.138000+00:00',
            name: 'Promozione Linkedin - Corso Giuseppe Garibaldi, 203, 84122 Salerno (SA)',
            locationID: '651559b41ba4dd76e29b6907',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address:
                'Corso Giuseppe Garibaldi, 203, 84122 Salerno (SA)',
            statusAnalisi: 1,
            timestampAnalisi: '2023-09-29T08:56:45.054000+00:00',
            from: 'giggi spa',
            code: 4,
            columns: [
                {
                    id: 'PASW60aGfEcv',
                    name: '*Da 0 a 10, con quale probabilità consiglieresti Calton ad amici e colleghi? *',
                    type: 'nps',
                    varsType: 'integer',
                    isRating: false,
                    isNPS: true,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 'vaS2fl0JacY7',
                    name: '*Quali sono i principali motivi della tua valutazione?*',
                    type: 'long_text',
                    varsType: 'string',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: true,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 'CsThm5ihgciu',
                    name: 'First name',
                    type: 'short_text',
                    varsType: 'string',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: true,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 'LaCCIUvMygxQ',
                    name: 'Last name',
                    type: 'short_text',
                    varsType: 'string',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: true,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 'XIzxOyfoLfKK',
                    name: 'Phone number',
                    type: 'phone_number',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: true,
                },
                {
                    id: '9NFeKirIfSOP',
                    name: 'Email',
                    type: 'email',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: true,
                },
                {
                    id: '0h96OewGFGlA',
                    name: 'Company',
                    type: 'short_text',
                    varsType: 'string',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: true,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 'y9BR75WHQ0h7',
                    name: '*Esprimo il mio consenso al trattamento dei dati personali per ricevere via notizie, aggiornamenti e promozione da Calton*',
                    type: 'legal',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: true,
                },
                {
                    id: 'OY8bfTnrFsmi',
                    name: '*Vuoi lasciarci una recensione?*',
                    type: 'yes_no',
                    varsType: 'boolean',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 1,
                    name: 'data_risposta',
                    type: 'mydatetime',
                    varsType: 'datetime',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: true,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 2,
                    name: 'data_inizio_risposta',
                    type: 'datetime',
                    varsType: 'datetime',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 3,
                    name: 'durata',
                    type: 'time',
                    varsType: 'timestamp',
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                    visible: false,
                },
                {
                    id: 'aoeplndzdl',
                    name: 'Sent_*Quali sono i principali motivi della tua valutazione?*',
                    type: 'integer',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: true,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                },
                {
                    id: 'lislrnglvw',
                    name: 'topics_*Quali sono i principali motivi della tua valutazione?*',
                    type: 'list',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: true,
                },
                {
                    id: 'dqsftmsfcl',
                    name: 'Sent_First name',
                    type: 'integer',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: true,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                },
                {
                    id: 'ivcjawgcgj',
                    name: 'topics_First name',
                    type: 'list',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: true,
                },
                {
                    id: 'jogdhtptln',
                    name: 'Sent_Last name',
                    type: 'integer',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: true,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                },
                {
                    id: 'epwedaoaod',
                    name: 'topics_Last name',
                    type: 'list',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: true,
                },
                {
                    id: 'fuodxhibcm',
                    name: 'Sent_Company',
                    type: 'integer',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: true,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: false,
                },
                {
                    id: 'vshhdnbsvh',
                    name: 'topics_Company',
                    type: 'list',
                    varsType: null,
                    isRating: false,
                    isNPS: false,
                    toAnalyse: false,
                    isTitle: false,
                    isDataFeedback: false,
                    isSentiment: false,
                    isGoogleID: false,
                    isAnswer: false,
                    isUrl: false,
                    isReviewer: false,
                    isOriginal: false,
                    isTopic: true,
                },
            ],
            typeformID: 'PSmTcIZW',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 18,
                    completion_rate: 100,
                    responses_count: 5,
                    total_visits: 6,
                    unique_visits: 4,
                },
                fields: [
                    {
                        id: 'PASW60aGfEcv',
                        title: '*Da 0 a 10, con quale probabilità consiglieresti Calton ad amici e colleghi? *',
                        label: '1',
                        ref: '01HBDPER5V17EV9SWD89VABX44',
                        views: 14,
                        dropoffs: 8,
                        type: 'nps',
                    },
                    {
                        id: 'vaS2fl0JacY7',
                        title: '*Quali sono i principali motivi della tua valutazione?*\n',
                        label: '2',
                        ref: '6984e99e-62fc-42d8-9593-93d6e714170e',
                        views: 6,
                        dropoffs: 0,
                        type: 'long_text',
                    },
                    {
                        id: 'y3Ny1mFYLZyE',
                        title: '*Se vuoi, puoi lasciarti i tuoi contatti:*',
                        label: '3',
                        ref: '59a7c4d4-740c-48f0-8e6c-7b20d049f6d9',
                        views: 6,
                        dropoffs: 0,
                        type: 'contact_info',
                    },
                    {
                        id: 'y9BR75WHQ0h7',
                        title: '*Esprimo il mio consenso al trattamento dei dati personali per ricevere via notizie, aggiornamenti e promozione da Calton*',
                        label: '4',
                        ref: 'f1063d3a-d445-43ee-886d-678dc8104cd5',
                        views: 6,
                        dropoffs: 1,
                        type: 'legal',
                    },
                    {
                        id: 'OY8bfTnrFsmi',
                        title: '*Vuoi lasciarci una recensione?*',
                        label: '5',
                        ref: 'ebff4c6c-cfd4-4162-8336-da004857c498',
                        views: 5,
                        dropoffs: 0,
                        type: 'yes_no',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '6548acc1e19aa7ae186f07f7',
            createdAt: '2023-11-06T09:07:13.277000+00:00',
            name: 'test - undefined',
            locationID: null,
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: '',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'OQwxixbU',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [
                    {
                        id: 'AcY6Mr9oLBPx',
                        title: 'test',
                        label: '1',
                        ref: '01HEHY6TVW2NCSDR21AQNH8N6N',
                        views: 1,
                        dropoffs: 1,
                        type: 'short_text',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '655f0fed2496620fc532213e',
            createdAt: '2023-11-23T08:40:13.758000+00:00',
            name: 'test - undefined',
            locationID: null,
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: '',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'uslQ7No8',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [],
            },
            children: null,
        },
        {
            _id: '661d4b714790e1fdd03bc76f',
            createdAt: '2024-04-15T15:44:49.920000+00:00',
            name: "NPS - Via A. Balsamo, 10, 80065 Sant'Agnello (NA)",
            locationID: '64b79b972c131f0828e55961',
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: "Via A. Balsamo, 10, 80065 Sant'Agnello (NA)",
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'xcXppocJ',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [
                    {
                        id: 'FQ3fv1cDJtC0',
                        title: 'Quanto consiglieresti il nostro supermercato ad amici e parenti da 1 a 10?',
                        label: '1',
                        ref: '01HVH6YE7C3AP03PBVCXQ9QKG3',
                        views: 4,
                        dropoffs: 4,
                        type: 'rating',
                    },
                ],
            },
            children: null,
        },
        {
            _id: '66601a160bac942433a24fdd',
            createdAt: '2024-06-05T07:56:06.313000+00:00',
            name: 'test no location - undefined',
            locationID: null,
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: '',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'FgA4TSk2',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [],
            },
            children: null,
        },
        {
            _id: '66601aaa0bac942433a24fde',
            createdAt: '2024-06-05T07:58:34.654000+00:00',
            name: 'test no location with answer - undefined',
            locationID: null,
            idProduct: null,
            idProductParent: null,
            productName: null,
            variations: null,
            formatted_address: '',
            statusAnalisi: 0,
            timestampAnalisi: null,
            from: 'giggi spa',
            code: 4,
            columns: [],
            typeformID: 'NNbUgkfa',
            idCompetitor: null,
            competitorName: null,
            typeformInfo: {
                summary: {
                    average_time: 0,
                    completion_rate: 0,
                    responses_count: 0,
                    total_visits: 0,
                    unique_visits: 0,
                },
                fields: [
                    {
                        id: 'WN4cfi5dNmmc',
                        title: 'test va?',
                        label: '1',
                        ref: '01HZKPGHYBMCEW1D3PKP1CKNCM',
                        views: 3,
                        dropoffs: 3,
                        type: 'short_text',
                    },
                    {
                        id: 'opwM53XC8sBO',
                        title: 'secondo me no',
                        label: '2',
                        ref: '01HZKPH0X32A6YCHGZPPFHRTVZ',
                        views: 0,
                        dropoffs: 0,
                        type: 'multiple_choice',
                    },
                ],
            },
            children: null,
        },
    ]*/

    const surveys = HomeService.getSourcesHome(
        allFilters,
        getNoCodeFromPlatfrom(),
        true,
        undefined,
        undefined,
        undefined
    )?.data?.data

    const [pagination, setPagination] = React.useState<PaginationState>({
        pageIndex: 0,
        pageSize: 20,
    })
    const changePage = (direction: any) => {
        if (direction === 'next') {
            setPagination({
                pageIndex: pagination.pageIndex + 1,
                pageSize: pagination.pageSize,
            })
        } else if (direction === 'previous') {
            setPagination({
                pageIndex: pagination.pageIndex - 1,
                pageSize: pagination.pageSize,
            })
        } else {
            const number = Number(direction)
            //TODO: we need to paginate the api
            /* if (
                number > 0 &&
                number <= Math.ceil(surveys?.countFeed / pagination.pageSize)
            ) {
                setPagination({
                    pageIndex: number - 1,
                    pageSize: pagination.pageSize,
                })
            } else {
                setPagination({
                    pageIndex: 0,
                    pageSize: pagination.pageSize,
                })
            }*/
        }
    }

    const changeElementsPerPage = (e: any) => {
        setPagination({
            pageIndex: 0,
            pageSize: e.value,
        })
    }

    const trackerData = [
        {
            label: t('Media tasso di completamento'),
            value: 200000,
            total: 15000,
        },
    ]

    return (
        <PageContainer>
            <PageHeader heading={t('Home')} subheading={true}></PageHeader>
            <div className={styles.container}>
                <div className={styles.headerContainer}>
                    <div className={styles.itemContainer}>
                        <InfoCard
                            value={16}
                            label={t('Sondaggi creati')}
                            icon={'surveyIconSvg'}
                        />
                    </div>
                    <div className={styles.itemContainer}>
                        <InfoCard
                            value={64}
                            label={t('Totale domande')}
                            icon={'questionIconSvg'}
                        />
                    </div>
                    <div className={styles.itemContainer}>
                        <TrackerCard data={trackerData} maxHeight={true} />
                    </div>
                    <div className={styles.itemContainer}>
                        <TierListCard
                            tierList={tierList}
                            label={t('dei sondaggi')}
                        />
                    </div>
                </div>
                <div className={styles.navigatorRow}>
                    <div className={styles.btnContainer}>
                        <Button
                            size={'small'}
                            customColor={'#E9E7EC'}
                            customTextColor={'black'}
                        >
                            {t('Data')}
                        </Button>
                    </div>
                    <div>
                        <PageNavigator
                            totalElements={100 /*surveys?.countFeed*/}
                            currentPage={pagination.pageIndex}
                            pageElements={pagination.pageSize}
                            changeElementsPerPage={changeElementsPerPage}
                            changePage={changePage}
                        />
                    </div>
                </div>
                <div className={styles.reviewsContainer}>
                    {surveys?.map((survey: any, idx: number) => {
                        return (
                            <CardSurvey
                                key={idx}
                                id={survey?._id}
                                elm={survey}
                                name={survey?.name}
                                userStart={
                                    survey?.typeformInfo?.summary?.total_visits
                                }
                                completition={
                                    survey?.typeformInfo?.summary
                                        ?.completion_rate
                                }
                                time={moment
                                    .utc(
                                        survey?.typeformInfo?.summary
                                            ?.average_time * 1000
                                    )
                                    .format('mm:ss')}
                                sentiment={survey?.meanSentiment}
                                response={
                                    survey?.typeformInfo?.summary
                                        ?.responses_count
                                }
                                date={moment
                                    .utc(survey?.createdAt)
                                    .format('DD/MM/YYYY')}
                                index={idx}
                            />
                        )
                    })}
                </div>
            </div>
        </PageContainer>
    )
}

export default Reviews
